server:
  port: 8080

spring:
  datasource:
    name: mydata
    url: jdbc:mysql://192.169.1.66:3306/springboottest?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=CTT&useUnicode=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 使用druid数据源
  type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:/templates/


mybatis:
  mapper-locations: classpath:mapping/*.xml  #classpath就是应用程序resources的路径
  type-aliases-package: com.springboot.demo

logging:
  level:
    com:
      spring:
        jiminshiro:
          mapper: debug
